export type ItemEventName = 'anchorShow'
  | 'anchorActived'
  | 'nodeState'
  | 'nodeState:default'
  | 'nodeState:selected'
  | 'nodeState:matched'
  | 'nodeState:hover'
  | 'edgeState'
  | 'edgeState:default'
  | 'edgeState:hover'
  | 'edgeState:selected'
  | 'edgeState:preselection'
